#!/usr/bin/env python3
"""
GitHub Sync Tool - Dual Workflow Support

Version: 1.0.5

This version supports syncing both:
1. Manual changes made directly by the user.
2. Changes made by an external agent (with automated testing).

Enhancements:
- Supports feature branch functionality by default.
- Allows testing of agent-generated files locally with preset validation workflow.
"""

import subprocess
import sys
import os
from pathlib import Path
from typing import Tuple, Optional

class GitHubSyncTool:
    """GitHub Sync Tool with dual workflows."""
    
    VERSION = "1.0.5"  # Update this version number as needed

    def __init__(self):
        self.repo_path = Path.cwd()
        self.feature_branch = "feature/agent-output"
        self.agent_test_cmd = ['python3', 'agent_generated_file.py']  # Example agent test

    def is_git_repo(self) -> bool:
        """Check if current directory is a Git repository."""
        try:
            subprocess.run(['git', 'rev-parse', '--git-dir'], cwd=self.repo_path, check=True, capture_output=True)
            return True
        except subprocess.CalledProcessError:
            return False

    def switch_to_feature_branch(self) -> Tuple[bool, str]:
        """Ensure working on the feature branch."""
        try:
            subprocess.run(['git', 'checkout', '-B', self.feature_branch], cwd=self.repo_path, check=True)
            return True, f"Switched to feature branch: {self.feature_branch}"
        except subprocess.CalledProcessError as e:
            return False, f"Error switching to feature branch: {e.stderr}"

    def test_agent_files(self) -> Tuple[bool, str]:
        """Test files generated by the agent."""
        try:
            subprocess.run(self.agent_test_cmd, cwd=self.repo_path, check=True)
            return True, "✓ Agent-generated files tested successfully."
        except subprocess.CalledProcessError as e:
            return False, f"✗ Agent-generated files testing failed. Error:\n{e.stderr}"

    def sync_to_github(self, commit_message: Optional[str] = None, is_agent_workflow=False) -> Tuple[bool, str]:
        """
        Sync changes to GitHub, with separate workflows for manual and agent-generated changes.
        """
        if not self.is_git_repo():
            return False, "Error: Not in a git repository."
        
        output = []

        # Switch to feature branch
        output.append("Step 1: Switching to feature branch...")
        success, message = self.switch_to_feature_branch()
        output.append(message)
        if not success:
            return False, "\n".join(output)

        # If agent workflow, test before syncing
        if is_agent_workflow:
            output.append("\nStep 2: Testing agent-generated files...")
            success, message = self.test_agent_files()
            output.append(message)
            if not success:
                # If testing failed, return with an appropriate message
                output.append("\n✗ Aborting sync because agent tests failed.")
                return False, "\n".join(output)
        else:
            output.append("\nStep 2: Skipping testing (manual workflow)...")

        try:
            # Stage all changes
            output.append("\nStep 3: Staging all changes...")
            subprocess.run(['git', 'add', '.'], cwd=self.repo_path, check=True)
            output.append("✓ Changes staged successfully.")

            # Commit changes
            output.append("\nStep 4: Committing changes...")
            if not commit_message:
                commit_message = "Sync: Manual or agent-generated changes"
            subprocess.run(['git', 'commit', '-m', commit_message], cwd=self.repo_path, check=True)
            output.append(f"✓ Changes committed: {commit_message}")

            # Push to feature branch
            output.append("\nStep 5: Pushing changes to GitHub...")
            subprocess.run(['git', 'push', '-u', 'origin', self.feature_branch], cwd=self.repo_path, check=True)
            output.append("✓ Changes pushed successfully.")

            return True, "\n".join(output)

        except subprocess.CalledProcessError as e:
            output.append(f"Error during sync: {e.stderr}")
            return False, "\n".join(output)

    def sync_from_github(self) -> Tuple[bool, str]:
        """Sync changes from GitHub to the local repository."""
        if not self.is_git_repo():
            return False, "Error: Not in a git repository."
        
        output = []

        try:
            # Stash local changes
            output.append("Step 1: Stashing local changes (if any)...")
            subprocess.run(['git', 'stash'], cwd=self.repo_path, check=False)
            output.append("✓ Local changes stashed.")

            # Pull changes
            output.append("Step 2: Pulling changes from GitHub...")
            subprocess.run(['git', 'pull', '--no-rebase'], cwd=self.repo_path, check=True)
            output.append("✓ Changes pulled successfully.")

            # Reapply stashed changes
            output.append("Step 3: Reapplying stashed changes...")
            subprocess.run(['git', 'stash', 'pop'], cwd=self.repo_path, check=False)
            output.append("✓ Stashed changes reapplied (if any).")

            return True, "\n".join(output)

        except subprocess.CalledProcessError as e:
            return False, f"{e.stderr}"


def print_menu():
    """Print the main menu options."""
    print("\n" + "=" * 60)
    print(f"GitHub Sync Tool - Main Menu (v{GitHubSyncTool.VERSION})")
    print("=" * 60)
    print("1. Sync Files with Manual Changes")
    print("2. Sync Files with Agent-Generated Changes")
    print("3. Pull Changes from GitHub")
    print("4. Test Agent Files Locally")
    print("5. Exit")
    print("=" * 60)


def main():
    """Main entry point."""
    print("\n🚀 GitHub Sync Tool - Dual Workflow Support (v1.0.0)")
    print("Repository:", Path.cwd())
    tool = GitHubSyncTool()

    while True:
        print_menu()
        choice = input("\nEnter your choice (1-5): ").strip()

        if choice == '1':
            # Manual changes
            commit_msg = input("Enter commit message (or press Enter for default): ").strip()
            success, message = tool.sync_to_github(commit_msg, is_agent_workflow=False)
        elif choice == '2':
            # Agent-generated changes
            commit_msg = input("Enter commit message (or press Enter for default): ").strip()
            success, message = tool.sync_to_github(commit_msg, is_agent_workflow=True)
        elif choice == '3':
            # Pull changes
            success, message = tool.sync_from_github()
        elif choice == '4':
            # Test agent files locally
            success, message = tool.test_agent_files()
        elif choice == '5':
            print("\n👋 Goodbye!")
            sys.exit(0)
        else:
            success, message = False, "Invalid choice. Please select an option between 1 and 5."

        print("\n" + message)
        input("\nPress Enter to continue...")


if __name__ == "__main__":
    main()
